<#
.SYNOPSIS
    Shared data and helpers for windows-utf8-fix scripts.
    Dot-source this from any script that needs the constants.

.EXAMPLE
    . "$PSScriptRoot\common.ps1"
#>

# ─── Reusable singletons ──────────────────────────────────────────────────
$script:UTF8NoBOM = [System.Text.UTF8Encoding]::new($false)

# ─── Sentinel block markers ──────────────────────────────────────────────
$BLOCK_BEGIN = '# >>> windows-utf8-fix v1.2.0 BEGIN >>>'
$BLOCK_END   = '# <<< windows-utf8-fix v1.2.0 END <<<'

# ─── PowerShell profile template ─────────────────────────────────────────
$PROFILE_BODY = @"

$BLOCK_BEGIN
# Generated by windows-utf8-fix skill. Safe to delete this block to uninstall.
`$OutputEncoding = [System.Text.UTF8Encoding]::new(`$false)
[Console]::InputEncoding  = [System.Text.UTF8Encoding]::new(`$false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new(`$false)
chcp 65001 | Out-Null

# Env vars honored by Python, Git Bash, Node, Java, Ruby
`$env:LC_ALL            = 'C.UTF-8'
`$env:LANG              = 'C.UTF-8'
`$env:PYTHONIOENCODING  = 'utf-8'
`$env:PYTHONUTF8        = '1'
`$env:JAVA_TOOL_OPTIONS = '-Dfile.encoding=UTF-8'
`$env:RUBYOPT           = '-Eutf-8'
$BLOCK_END
"@

# ─── User-level environment variables ────────────────────────────────────
# Single source of truth: install / standalone / diagnose / uninstall all use this
$script:EnvDefaults = [ordered]@{
    'LC_ALL'            = 'C.UTF-8'
    'LANG'              = 'C.UTF-8'
    'PYTHONIOENCODING'  = 'utf-8'
    'PYTHONUTF8'        = '1'
    'JAVA_TOOL_OPTIONS' = '-Dfile.encoding=UTF-8'
    'RUBYOPT'           = '-Eutf-8'
}
# Expose as a global alias for scripts that dot-source this
$EnvDefaults = $script:EnvDefaults

# ─── Git global config defaults ──────────────────────────────────────────
$script:GitDefaults = [ordered]@{
    'core.quotepath'         = 'false'
    'i18n.commitencoding'    = 'utf-8'
    'i18n.logoutputencoding' = 'utf-8'
    'gui.encoding'           = 'utf-8'
}
$GitDefaults = $script:GitDefaults

# ─── VS Code family desired settings ─────────────────────────────────────
$script:VSCodeSettings = [ordered]@{
    'terminal.integrated.env.windows' = [ordered]@{
        'PYTHONIOENCODING' = 'utf-8'
        'LC_ALL'           = 'C.UTF-8'
        'LANG'             = 'C.UTF-8'
        'PYTHONUTF8'       = '1'
    }
    'files.encoding'         = 'utf8'
    'files.autoGuessEncoding' = $true
}
$VSCodeSettings = $script:VSCodeSettings

# ─── Zed desired settings ────────────────────────────────────────────────
$script:ZedSettings = [ordered]@{
    'terminal' = [ordered]@{
        'env' = [ordered]@{
            'PYTHONIOENCODING' = 'utf-8'
            'LC_ALL'           = 'C.UTF-8'
            'LANG'             = 'C.UTF-8'
        }
    }
}
$ZedSettings = $script:ZedSettings

# ─── Qoder desired settings (flat key:value in config.yaml) ───────────────
# Qoder (Alibaba) reads UTF-8 env vars automatically. We just need to ensure
# the user-level env vars are set (handled by Layer 1). No yaml patch needed
# unless we want to set Qoder-specific options. Keep empty for now.
$script:QoderSettings = [ordered]@{}
$QoderSettings = $script:QoderSettings

# ─── IDE candidate paths ─────────────────────────────────────────────────
# Format: kind = 'json' | 'yaml' | 'zed'
$script:IDEPaths = @(
    # VS Code family (Electron-based, settings.json under %APPDATA%)
    @{ Name = 'VS Code';          Kind = 'json'; Path = "$env:APPDATA\Code\User\settings.json" },
    @{ Name = 'VS Code Insiders'; Kind = 'json'; Path = "$env:APPDATA\Code - Insiders\User\settings.json" },
    @{ Name = 'VSCodium';         Kind = 'json'; Path = "$env:APPDATA\VSCodium\User\settings.json" },
    # Cursor family (VS Code forks)
    @{ Name = 'Cursor';           Kind = 'json'; Path = "$env:APPDATA\Cursor\User\settings.json" },
    @{ Name = 'Windsurf';         Kind = 'json'; Path = "$env:APPDATA\Windsurf\User\settings.json" },
    # Trae (ByteDance) — CN edition + Work (formerly TRAE SOLO)
    @{ Name = 'Trae CN';          Kind = 'json'; Path = "$env:APPDATA\Trae CN\User\settings.json" },
    @{ Name = 'Trae Work';        Kind = 'json'; Path = "$env:APPDATA\Trae Work\User\settings.json" },
    @{ Name = 'Trae Solo';        Kind = 'json'; Path = "$env:APPDATA\Trae Solo\User\settings.json" },
    # Qoder (Alibaba) — uses YAML not JSON
    @{ Name = 'Qoder';            Kind = 'yaml'; Path = "$env:APPDATA\Qoder\config.yaml" },
    # CodeBuddy (Tencent) — uses %USERPROFILE% not %APPDATA%
    @{ Name = 'CodeBuddy';        Kind = 'json'; Path = "$env:USERPROFILE\.codebuddy\settings.json" },
    # Zed
    @{ Name = 'Zed';              Kind = 'zed';  Path = "$env:APPDATA\Zed\settings.json" }
)
$IDEPaths = $script:IDEPaths

# ─── Helper functions ────────────────────────────────────────────────────
function global:Write-Section([string]$title) {
    Write-Host "`n=== $title ===" -ForegroundColor Cyan
}

function global:Write-Step([string]$msg) {
    Write-Host "`n▶ $msg" -ForegroundColor Cyan
}

function global:Write-Ok([string]$msg) {
    Write-Host "  ✓ $msg" -ForegroundColor Green
}

function global:Write-Warn([string]$msg) {
    Write-Host "  ⚠ $msg" -ForegroundColor Yellow
}

function global:Write-Skip([string]$msg) {
    Write-Host "  · $msg" -ForegroundColor DarkGray
}

function global:Write-Err([string]$msg) {
    Write-Host "  ✗ $msg" -ForegroundColor Red
}

# ─── Utility: resolve script directory even when dot-sourced ─────────────
function global:Get-ScriptRoot {
    if ($PSScriptRoot) { return $PSScriptRoot }
    if ($MyInvocation.MyCommand.Path) {
        return Split-Path $MyInvocation.MyCommand.Path -Parent
    }
    return $PWD.Path
}

# ─── Utility: merge JSON hashtable, returns ($hashtable, $changed) ───────
# Supports both PS 7+ (-AsHashtable) and PS 5.1 (PSCustomObject conversion)
function global:Merge-SettingsJson {
    param(
        [string]$Path,
        [hashtable]$Desired
    )
    $raw = [System.IO.File]::ReadAllText($Path, $script:UTF8NoBOM)
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return @{ Json = @{}; Changed = $true }
    }

    $json = if ($PSVersionTable.PSVersion.Major -ge 7) {
        $raw | ConvertFrom-Json -AsHashtable -ErrorAction Stop
    } else {
        # PS 5.1: ConvertFrom-Json returns PSCustomObject, convert to hashtable
        $obj = $raw | ConvertFrom-Json -ErrorAction Stop
        ConvertTo-HashtablePS5 $obj
    }

    $changed = $false
    foreach ($k in $Desired.Keys) {
        if (-not $json.ContainsKey($k)) {
            $json[$k] = $Desired[$k]
            $changed = $true
        }
    }

    return @{ Json = $json; Changed = $changed }
}

# ─── Utility: PSCustomObject → Hashtable (PS 5.1 compat) ─────────────────
function ConvertTo-HashtablePS5 {
    param($obj)
    if ($null -eq $obj) { return $null }
    $ht = @{}
    foreach ($p in $obj.PSObject.Properties) {
        if ($p.Value -is [PSCustomObject]) {
            $ht[$p.Name] = ConvertTo-HashtablePS5 $p.Value
        } elseif ($p.Value -is [Array]) {
            $arr = @()
            foreach ($item in $p.Value) {
                if ($item -is [PSCustomObject]) {
                    $arr += ConvertTo-HashtablePS5 $item
                } else {
                    $arr += $item
                }
            }
            $ht[$p.Name] = $arr
        } else {
            $ht[$p.Name] = $p.Value
        }
    }
    return $ht
}

# ─── Utility: write JSON file safely (with try/catch and report) ─────────
function global:Write-SettingsJson {
    param(
        [string]$Path,
        [hashtable]$Hashtable
    )
    $new = $Hashtable | ConvertTo-Json -Depth 10
    $new = $new -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText($Path, $new, $script:UTF8NoBOM)
}

# ─── Utility: backup a file before modification ──────────────────────────
function global:Backup-File {
    param([string]$Path)
    if (Test-Path $Path) {
        $ts = Get-Date -Format 'yyyyMMdd-HHmmss'
        $bak = "$Path.utf8fix-bak-$ts"
        Copy-Item $Path $bak -Force
        Write-Ok "Backup saved: $bak"
        return $bak
    }
    return $null
}

# ─── Utility: YAML (de)serializer for simple key:value / nested keys ─────
# Supports only the subset we need: "key: value", "  key: value", "key:\n  child: val"
# Comments (#) and blank lines are preserved untouched.
function ConvertFrom-SimpleYaml {
    param([string]$Text)
    $lines = $Text -split "`n"
    $result = [ordered]@{}
    $stack = @($result)        # path of nested hashtables
    $indentStack = @(-1)

    foreach ($line in $lines) {
        if ($line -match '^\s*#' -or $line -match '^\s*$') { continue }
        $indent = ($line -replace '^( *).*$', '$1').Length
        $content = $line.TrimEnd("`r")

        # Pop stack to find the right parent
        while ($indentStack.Count -gt 1 -and $indent -le $indentStack[-1]) {
            $stack = $stack[0..($stack.Count - 2)]
            $indentStack = $indentStack[0..($indentStack.Count - 2)]
        }

        if ($content -match '^(.*?):\s*$') {
            # Nested key start
            $key = $Matches[1].Trim()
            $child = [ordered]@{}
            $stack[-1][$key] = $child
            $stack += $child
            $indentStack += $indent
        } elseif ($content -match '^(.*?):\s*(.+?)\s*$') {
            $key = $Matches[1].Trim()
            $val = $Matches[2].Trim()
            # Strip surrounding quotes
            if ($val -match '^"(.*)"$') { $val = $Matches[1] }
            elseif ($val -match "^'(.*)'$") { $val = $Matches[1] }
            $stack[-1][$key] = $val
        }
    }
    return $result
}

function ConvertTo-SimpleYaml {
    param(
        [hashtable]$Hashtable,
        [int]$Indent = 0
    )
    $sb = New-Object System.Text.StringBuilder
    $pad = '  ' * $Indent
    foreach ($k in $Hashtable.Keys) {
        $v = $Hashtable[$k]
        $colon = ':'
        if ($v -is [hashtable]) {
            [void]$sb.AppendLine(($pad + $k + $colon))
            [void]$sb.Append((ConvertTo-SimpleYaml -Hashtable $v -Indent ($Indent + 1)))
        } elseif ($v -is [bool]) {
            [void]$sb.AppendLine(($pad + $k + $colon + ' ' + $v.ToString().ToLower()))
        } elseif ($v -match '[\s' + $colon + '#]') {
            [void]$sb.AppendLine(($pad + $k + $colon + ' "' + $v + '"'))
        } else {
            [void]$sb.AppendLine(($pad + $k + $colon + ' ' + $v))
        }
    }
    return $sb.ToString()
}

# ─── Utility: merge a flat settings hashtable into a YAML file ───────────
# Unlike JSON, YAML is positional: append new keys at the end of the file.
# Existing keys (matched by "key:") are updated in-place; otherwise appended.
function global:Merge-SettingsYaml {
    param(
        [string]$Path,
        [hashtable]$Desired
    )
    $raw = [System.IO.File]::ReadAllText($Path, $script:UTF8NoBOM)
    $lines = $raw -split "`n"
    $out = New-Object System.Text.StringBuilder
    $existingKeys = @{}
    $found = $false

    foreach ($line in $lines) {
        $matched = $false
        foreach ($k in $Desired.Keys) {
            if ($line -match "^( *)$([regex]::Escape($k)):\s*") {
                $existingKeys[$k] = $true
                $matched = $true
                break
            }
        }
        [void]$out.AppendLine($line.TrimEnd("`r"))
    }

    $changed = $false
    $appended = New-Object System.Text.StringBuilder
    foreach ($k in $Desired.Keys) {
        if ($existingKeys.ContainsKey($k)) { continue }
        $v = $Desired[$k]
        $valStr = if ($v -is [bool]) { $v.ToString().ToLower() }
                  elseif ($v -match '[\s:#]') { '"' + $v + '"' }
                  else { "$v" }
        [void]$appended.AppendLine(($k + ': ' + $valStr))
        $changed = $true
    }

    $raw2 = $out.ToString().TrimEnd("`n")
    if ($appended.Length -gt 0) {
        $raw2 = $raw2 + "`n" + $appended.ToString().TrimEnd("`n") + "`n"
    } else {
        $raw2 = $raw2 + "`n"
    }

    return @{ Content = $raw2; Changed = $changed }
}

# ─── Utility: write content to file atomically ───────────────────────────
function global:Write-FileUtf8 {
    param(
        [string]$Path,
        [string]$Content
    )
    $Content = $Content -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText($Path, $Content, $script:UTF8NoBOM)
}